name: vproflie actions
on: workflow_dispatch
env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: gitops
  EKS_CLUSTER: gitops2
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Maven test
        run: mvn test
      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      #Setup java 11
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      #Setup sonar-scanner
      - name: Setup Sonar Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }} #OPTIONAL

  BUILD_AND_PUSHLISH:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "ACCESS_KEY => ${AWS_ACCESS_KEY_ID}"
          echo "SECRET_KEY length => ${AWS_SECRET_ACCESS_KEY}"
          echo "REGISTRY => ${REGISTRY}"

      # 1. Cấu hình AWS credentials từ secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 2. Login vào ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin ${{ secrets.REGISTRY }}

      # 3. Build & Upload image to ECR (giữ repo + tag như code cũ)
      - name: Build & Upload image to ECR
        run: |
          IMAGE=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }}:${GITHUB_RUN_NUMBER}
          LATEST=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest

          echo "Build image $IMAGE"
          docker build -t $IMAGE -f ./Dockerfile .

          echo "Push image với tag run_number"
          docker push $IMAGE

          echo "Tag thêm latest và push"
          docker tag $IMAGE $LATEST
          docker push $LATEST
